/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8e87c266-4559-40a9-98d2-dcff6477249e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_5KJIFO4oN",
    "aws_user_pools_web_client_id": "6d8h5c7n3k16sik1pbpqtrf5pa",
    "oauth": {
        "domain": "contactsfindab2cf049-ab2cf049-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:5173/contactsfind-ui/,https://anborg.github.io/contactsfind-ui/,https://wdnvmhba710:8082/,https://localhost:8080/,http://localhost:5173/contactsfind-ui/",
        "redirectSignOut": "http://localhost:5173/contactsfind-ui/signout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE",
        "AMAZON"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
